import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* 🔽 Mobile Fixed CTA */}
        <div className="mobile-cta">
          <a href="tel:051-714-3396" className="cta-btn call">
            📞 전화
          </a>

          {/* ✅ 기존에 만들어둔 문자 폼(id="sms-lead")으로 이동 */}
          <a href="/#sms-lead" className="cta-btn sms">
            ✉️ 문자요청
          </a>
        </div>
      </body>
    </html>
  );
}
